Repository sojinjang/hansuldam, pull requests merged in 2022-11, with the labels that each got.

#2 [221116] [FE] key 상수 파일 분리, 로그아웃시 장바구니 비우기
  src/views/adult_certification/adult_certification.js
  src/views/api.js
  src/views/cart/cart.js
  src/views/category_page/category_page.js
  src/views/constants/ErrorMessage.js
  src/views/constants/Keys.js
  src/views/login/login.js
  src/views/order_pay_member/order_pay_member.js
  src/views/order_pay_nonmember/order_pay_nonmember.js
  src/views/template/getHeaderFooter.js
  src/views/template/header/header.js
  src/views/utils/localStorage.js
Labels: enhancement, FE

#3 [221116] [FE] 페이지네이션 버그 고치기, 장바구니 최초 담기 버그 고치기
  src/views/admin/order_admin.js
  src/views/admin/product_admin.js
  src/views/category_page/category_page.css
  src/views/category_page/category_page.js
  src/views/product_detail/product_detail.js
  src/views/template/header/header.js
Labels: fe, debug

#6 [221117] [FE] 소진 리팩토링 완료
  src/views/cart/cart.js
Labels: fe

#7 [221117] [FE] 주문하기 클릭 시 장바구니 비우기 롤백
  src/views/product_detail/product_detail.js
Labels: fe

#9 [221118] [BE] router 주소 개선
  src/app.js
  src/db/models/category-model.js
  src/db/models/order-model.js
  src/db/models/product-model.js
  src/db/models/user-model.js
  src/routers/admin-router.js
  src/routers/auth-router.js
  src/routers/cart-router.js
  src/routers/category-router.js
  src/routers/comment-router.js
  src/routers/index.js
  src/routers/order-router.js
  src/routers/product-router.js
  src/routers/user-router.js
  src/services/category-service.js
  src/services/order-service.js
  src/services/product-service.js
  src/services/user-service.js
  src/utils/index.js
Labels: be

#10 [221118] [BE] 장바구니 기능 개선 및 추가
  src/db/models/product-model.js
  src/routers/cart-router.js
  src/routers/order-router.js
  src/services/cart-service.js
  src/services/category-service.js
  src/services/index.js
  src/services/order-service.js
  src/services/user-service.js
  src/utils/index.js
  src/utils/sorting-cart.js
Labels: be

#11 [221118] [FE] 상품 상세 페이지 내 수량 조절 옵션 추가
  src/views/admin/category_admin.js
  src/views/admin/order_admin.js
  src/views/admin/product_admin.js
  src/views/category_page/category_page.js
  src/views/constants/Keys.js
  src/views/event_page/event_page.js
  src/views/home/home.html
  src/views/home/home.js
  src/views/product_detail/product_detail.css
  src/views/product_detail/product_detail.js
  src/views/template/header/header.js
  src/views/utils/useful_functions.js
Labels: bug, fe

#12 [221118] [FE] [BE] 다음 주소 검색 기능 추가 및 적용
  src/db/schemas/user-schema.js
  src/views/join/join-success.css
  src/views/join/join-success.html
  src/views/join/join-success.js
  src/views/utils/findAddress.js
Labels: fe, be

#13 [221119] [BE] cart 응답 타입 변경
  src/utils/sorting-cart.js
Labels: be

#14 [221119] [FE] 로그인된 회원 장바구니 기능 구현, 주문 페이지를 포함한 리팩토링
  src/routers/views-router.js
  src/views/adult_certification/adult_certification.js
  src/views/cart/cart.js
  src/views/constants/ApiUrl.js
  src/views/login/login.js
  src/views/order_pay/order_completed.css
  src/views/order_pay/order_completed.html
  src/views/order_pay/order_completed.js
  src/views/order_pay/order_pay.css
  src/views/order_pay/order_pay.html
  src/views/order_pay/order_pay.js
  src/views/order_pay_nonmember/order_completed.css
  src/views/order_pay_nonmember/order_completed.html
  src/views/order_pay_nonmember/order_completed.js
  src/views/order_pay_nonmember/order_pay_nonmember.css
  src/views/order_pay_nonmember/order_pay_nonmember.html
  src/views/order_pay_nonmember/order_pay_nonmember.js
  src/views/product_detail/product_detail.js
  src/views/template/getHeaderFooter.js
  src/views/template/header/header.js
  src/views/utils/cart.js
  src/views/utils/useful_functions.js
Labels: enhancement, fe

#15 [221119] [FE] 장바구니에서 체크된 상품만 주문페이지로 넘어가도록 수정
  src/views/cart/cart.js
  src/views/constants/Keys.js
  src/views/order_pay/order_pay.js
  src/views/product_detail/product_detail.js
  src/views/template/header/header.js
Labels: fe, debug

#16 [221119] [FE] 장바구니에서 주문완료하면 주문한 아이템만 장바구니에서 지워주는 기능 추가
  src/views/cart/cart.js
  src/views/order_pay/order_pay.js
  src/views/utils/cart.js
Labels: enhancement, fe

#17 [221119] [FE] 덮어씌워진 상품상세 페이지 코드 복구, 기능 추가
  src/views/product_detail/product_detail.js
  src/views/utils/cart.js
Labels: enhancement, fe, debug

#21 [221120] [BE] 필터링 조회 기능 추가
  src/db/models/product-model.js
  src/db/schemas/product-schema.js
  src/routers/product-router.js
  src/services/product-service.js
  src/utils/index.js
  src/utils/pagination.js
Labels: be

#22 [221120] [BE] 필터링 조회 기능 개선
  src/routers/product-router.js
  src/services/product-service.js
  src/utils/index.js
  src/utils/make-filterObj.js
Labels: be

#23 [221120] [FE] 관리자 페이지 - 상품 관리 버그 수정 및 카테고리 페이지 리팩토링
  src/views/admin/product_admin.js
  src/views/category_page/category_page.js
  src/views/product_detail/product_detail.css
  src/views/product_detail/product_detail.js
Labels: fe, debug

#24 perPage 기본값 9 로 수정
  src/routers/product-router.js
Labels: be

#25 fix: totalPage 형태 수정
  src/services/product-service.js
Labels: be

#26 [221121] [be] totalPage 타입 수정
  src/services/product-service.js
  src/utils/pagination.js
Labels: be, debug

#27 [221121] [BE] 이미지 업로드 기능 추가
  src/app.js
  src/db/schemas/order-schema.js
  src/db/schemas/product-schema.js
  src/routers/index.js
  src/services/product-service.js
  src/utils/multer.js
  src/views/img/products/강냉이 막걸리.jpg
  src/views/img/products/고도리 복숭아 와인.jpg
  src/views/img/products/나루 생 막걸리.jpg
  src/views/img/products/담은.jpg
  src/views/img/products/매실원주.jpg
  src/views/img/products/명품안동소주.jpg
  src/views/img/products/백련 미스티 살균 막걸리.jpg
  src/views/img/products/복순도가 손 막걸리.jpg
  src/views/img/products/붉은 원숭이.jpg
  src/views/img/products/서울의 밤.jpg
  src/views/img/products/서천 한산소곡주.jpg
  src/views/img/products/선운산 복분자주.jpg
  src/views/img/products/솔송주 약주.jpg
  src/views/img/products/술공방 9.0.jpg
  src/views/img/products/술취한 원숭이.jpg
  src/views/img/products/우주멜론미.jpg
  src/views/img/products/유채꽃, 제주.jpg
  src/views/img/products/진도 홍주.jpg
  src/views/img/products/혼디주.jpg
Labels: be

#28 [221121] [BE] 댓글 비회원 조회 가능으로 변경
  src/routers/comment-router.js
Labels: be

#30 [221122] [BE] 상품수정에서 image 변수 fix
  src/routers/product-router.js
Labels: be, debug

#31 [221122] [FE] 주소 검색 기능 추가
  src/views/join/join-success.html
  src/views/myPage/myPage.js
  src/views/order_pay/order_completed.js
  src/views/order_pay/order_pay.css
  src/views/order_pay/order_pay.html
  src/views/order_pay/order_pay.js
  src/views/user_information/change_address.js
  src/views/user_information/user_information.html
  src/views/user_information/user_information.js
Labels: fe

#32 [221122] [BE] 카테고리 기능 개선 + 상품 수정기능 fix
  src/db/models/category-model.js
  src/db/models/product-model.js
  src/routers/category-router.js
  src/services/category-service.js
  src/services/product-service.js
Labels: be, debug

#33 [221122] [FE] 이미지 업로드 구현 및 최적화
  src/routers/product-router.js
  src/services/product-service.js
  src/utils/pagination.js
  src/views/admin/admin.css
  src/views/admin/category_admin.js
  src/views/admin/order_admin.js
  src/views/admin/product_admin.js
  src/views/category_page/category_page.js
  src/views/home/home.js
  src/views/product_detail/product_detail.js
Labels: enhancement, fe

#35 [221123] [BE] 필터검색기능 수정
  src/utils/make-filterObj.js
Labels: be

#36 [221123] [BE] 상품 삭제 fix
  src/services/product-service.js
Labels: be, debug

#37 [221123] [BE] 로그인시 응답에 userId 추가
  src/routers/user-router.js
  src/services/user-service.js
Labels: be

#38 [221123] [BE] get 응답에 유저 fullname 추가
  src/db/models/comment-model.js
Labels: be

#39 [221123] [FE] 회원 주문내역 결제내역 컨테이너 추가
  src/views/order_list/order_list.css
  src/views/order_list/order_list.html
  src/views/order_list/order_list.js
Labels: fe

#41 [221124] [FE] 사용자정보페이지에 회원탈퇴 기능 추가
  src/views/user_information/user_information.html
  src/views/user_information/user_information.js
Labels: fe

#42 [221124] [BE] 주문취소 fix
  src/services/order-service.js
Labels: be

#44 [221124] [BE] 키워드 검색기능 추가
  src/routers/product-router.js
  src/services/product-service.js
  src/utils/make-filterObj.js
Labels: be

#45 [221124] [BE] auth 로그인 기능 개선
  src/db/schemas/user-schema.js
  src/routers/naver-router.js
  src/services/user-service.js
Labels: be

#46 [221124] [FE] 일부 코드 리팩토링
  src/views/myPage/myPage.js
  src/views/order_list/order_list.js
  src/views/user_information/change_address.js
  src/views/user_information/change_password.js
  src/views/user_information/change_phoneNumber.js
  src/views/user_information/change_user_information.js
  src/views/user_information/user_information.html
  src/views/user_information/user_information.js
Labels: fe

#48 [221124] [FE] 네이버 로그인 방식 변경, 로그인시 userId 쿠키에 저장
  src/views/adult_certification/adult_certification.js
  src/views/constants/ApiUrl.js
  src/views/constants/Keys.js
  src/views/login/login.js
  src/views/product_detail/review.css
  src/views/template/getHeaderFooter.js
  src/views/template/header/header.js
  src/views/utils/cookie.js
Labels: enhancement, fe

#50 [221125] 메인 컬러, 버튼 파일 추가
  src/views/template/main_style.css
Labels: fe, style

#51 [221125] [FE] 폰트 종류, 공통 폰트 사이즈와 버튼 추가
  src/views/template/main_style.css
Labels: fe, style

#52 [221125] [FE] 헤더에 마이페이지 추가, 함수이름 변경 등 사소한 리팩토링
  src/views/admin/product_admin.js
  src/views/product_detail/product_detail.js
  src/views/template/header/header.css
  src/views/template/header/header.js
Labels: fe

#53 [221125] [BE] 상품 샘플 이미지 추가
  src/views/img/products/감천 생막걸리.jpg
  src/views/img/products/국순당여주 프리미엄 려.jpg
  src/views/img/products/병영소주.jpg
  src/views/img/products/보은주 생막걸리.jpg
  src/views/img/products/아이비 허니비 와인.jpg
  src/views/img/products/지란지교 프리미엄 생약주.jpg
  src/views/img/products/천비향 악주.jpg
  src/views/img/products/청명주 백도자기 세트.jpg
  src/views/img/products/청명주 약주.jpg
  src/views/img/products/청수 화이트와인.jpg
  src/views/img/products/크라테 레드와인 미디엄드라이.jpg
Labels: be

#54 [221126] [FE] 상품 상세 페이지 핫픽스와 헤더 디자인 변화
  src/views/category_page/category_page.css
  src/views/img/search-icon.png
  src/views/product_detail/product_detail.css
  src/views/product_detail/product_detail.js
  src/views/template/footer/footer.css
  src/views/template/header/header.css
  src/views/template/header/header.js
Labels: enhancement, fe, debug

#56 [221128] [FE] 마이페이지 css작업
  src/views/myPage/myPage.css
  src/views/myPage/myPage.html
  src/views/myPage/myPage.js
Labels: fe, style

#57 [221128] [FE] 사용자정보페이지 css작업
  src/views/user_information/change_user_information.js
  src/views/user_information/user_information.css
  src/views/user_information/user_information.html
  src/views/user_information/user_information.js
Labels: fe, style

#58 [221128] [FE] 221128 주문내역페이지 css작업
  src/views/order_list/order_list.css
  src/views/order_list/order_list.html
  src/views/order_list/order_list.js
Labels: fe, style

#59 [221128] [FE] 헤더 검색창 디자인
  src/views/template/footer/footer.css
  src/views/template/header/header.css
  src/views/template/header/header.js
  src/views/template/main_style.css
Labels: fe, style

#60 [221128] [FE] 홈, 제품 상세 디자인
  src/views/home/home.css
  src/views/home/home.html
  src/views/img/carousel1.jpg
  src/views/img/carousel1.png
  src/views/img/carousel2.png
  src/views/img/carousel3.png
  src/views/img/carousel4.png
  src/views/img/carousel5.png
  src/views/img/icon_bundle.png
  src/views/img/icon_distilled_drinks.png
  src/views/img/icon_etc.png
  src/views/img/icon_fruit_wine.png
  src/views/img/icon_liquor.png
  src/views/img/icon_yakju.png
  src/views/img/logo.png
  src/views/product_detail/product_detail.css
Labels: fe, style

#61 [221128] [BE] update token expired time
  src/services/user-service.js
Labels: be

#62 [221128] [FE] 장바구니, 결제, 결제완료 페이지 디자인 및 추가 기능 작업 완료
  src/views/cart/cart.css
  src/views/cart/cart.html
  src/views/cart/cart.js
  src/views/order_pay/order_completed.css
  src/views/order_pay/order_completed.html
  src/views/order_pay/order_completed.js
  src/views/order_pay/order_pay.css
  src/views/order_pay/order_pay.html
  src/views/order_pay/order_pay.js
  src/views/template/main_style.css
Labels: enhancement, fe, style

#63 [221129] [FE] 사용자 정보페이지 css작업
  src/views/user_information/user_information.css
  src/views/user_information/user_information.html
Labels: fe, style

#64 [221129] [FE] 회원 주문내역 페이지 css작업
  src/views/order_list/order_list.css
  src/views/order_list/order_list.js
Labels: fe, style

#65 [221129] [FE] 마이페이지(+비회원 주문내역 페이지) css 작업
  src/views/myPage/myPage.css
Labels: fe, style

#66 [221129] [FE] 카테고리 페이지, 기획전 페이지 css 작업
  src/views/category_page/category_page.css
  src/views/category_page/category_page.js
  src/views/event_page/event_page.css
  src/views/event_page/event_page.html
  src/views/event_page/event_page.js
  src/views/img/carousel.jpg
  src/views/template/header/header.css
Labels: fe, style

#67 [221129] [FE] 기획전 페이지 버그 해결과 UI 통일
  src/views/category_page/category_page.css
  src/views/event_page/event_page.css
  src/views/event_page/event_page.js
Labels: fe, debug, style

#68 [221129] [BE] data: 상품 이미지 추가
  src/views/img/products/금산인삼주 금설.jpg
  src/views/img/products/명품안동소주 양반탈.jpg
  src/views/img/products/문배술 호리병 설 선물 전통주.jpg
  src/views/img/products/민속주 궁중술 왕주.jpg
  src/views/img/products/솔송주 명가원 산머루주.jpg
  src/views/img/products/홈파티 우주술 몽레브 오로라.jpg
Labels: be

#69 [221129] [FE] 장바구니 수량 카운트 구현, 관리자페이지 CSS 수정, 상품페이지 미디어쿼리 적용, 상품페이지 데이터 개수 조절
  src/views/admin/admin.css
  src/views/admin/admin.html
  src/views/admin/category_admin.js
  src/views/admin/order_admin.js
  src/views/admin/product_admin.js
  src/views/cart/cart.js
  src/views/category_page/category_page.css
  src/views/category_page/category_page.html
  src/views/category_page/category_page.js
  src/views/event_page/event_page.css
  src/views/event_page/event_page.js
  src/views/product_detail/product_detail.js
  src/views/template/header/header.js
Labels: enhancement, fe, style

#70 [221129] [FE] 로그인 페이지 css작업
  src/views/img/login.png
  src/views/img/naver_btnG_아이콘사각.png
  src/views/img/password.png
  src/views/login/login.css
  src/views/login/login.html
  src/views/login/login.js
Labels: fe, style

#71 [221129] [BE] 댓글 사진 데이터 추가
  src/views/img/comments/고도리 복숭아 와인 후기.jpeg
  src/views/img/comments/서울의밤 후기.jpg
  src/views/img/comments/우주멜론미.jpg
  src/views/img/comments/황금보리 후기.jpg
  src/views/img/products/황금 보리.jpg
Labels: be

#72 [221129] [BE] comment 삭제 버그 fix
  src/services/comment-service.js
Labels: be, debug

#73 [221130] [FE] 비밀번호찾기 페이지, 마이페이지, 주문내역 페이지 css수정
  src/views/find_password/find_password.css
  src/views/find_password/find_password.html
  src/views/myPage/myPage.css
  src/views/myPage/myPage.js
  src/views/order_list/order_list.css
  src/views/order_list/order_list.html
Labels: fe, debug, style

#74 [221130] [BE] 이미지 파일 이름 공백 제거
  src/views/img/comments/고도리복숭아와인후기.jpeg
  src/views/img/comments/서울의밤후기.jpg
  src/views/img/comments/황금보리후기.jpg
Labels: be, debug

#75 [221130] [FE] 로그인, 회원가입 페이지 css작업
  src/views/join/join-success.css
  src/views/join/join-success.html
  src/views/join/join-success.js
  src/views/join/join.css
  src/views/join/join.html
  src/views/login/login.css
Labels: fe, style

#77 [221130] [FE] 홈, 제품 상세페이지 css
  src/views/home/home.css
  src/views/home/home.html
  src/views/product_detail/product_detail.css
  src/views/product_detail/review.css
Labels: fe, style

#78 [221130] [FE] 리뷰 수정, 삭제 기능 구현 완료
  src/views/product_detail/product_detail.html
  src/views/product_detail/review.css
  src/views/product_detail/review_board.js
  src/views/product_detail/review_form.js
  src/views/utils/validator.js
Labels: enhancement, fe, style

#79 [221130] [FE] 페이지네이션 페이지화 구현
  src/views/category_page/category_page.js
  src/views/event_page/event_page.css
  src/views/home/home.css
  src/views/template/header/header.css
  src/views/template/header/header.js
Labels: enhancement, fe, style

#81 [221130] [BE] 안쓰는 라우터 삭제
  src/routers/image-router.js
Labels: be

#82 [221130] [FE] 마이페이지, 가입페이지, 성인인증페이지, ... 피드백 css수정
  src/views/adult_certification/adult_certification.css
  src/views/adult_certification/adult_certification.html
  src/views/join/join-success.css
  src/views/join/join.css
  src/views/join/join.html
  src/views/login/login.css
  src/views/myPage/myPage.css
  src/views/myPage/myPage.js
  src/views/order_list/order_list.css
  src/views/order_list/order_list.js
Labels: fe, style

#84 [221130] [FE] 알콜타입 아이콘 클릭 시 필터링 후 해당 상품 나열
  src/routers/views-router.js
  src/views/filter/filter.css
  src/views/filter/filter.html
  src/views/filter/filter.js
  src/views/home/home.html
  src/views/home/home.js
Labels: enhancement, fe

#85 [221201] [FE] 주문내역 페이지 버그 수정
  src/views/myPage/myPage.js
  src/views/order_list/order_list.css
  src/views/order_list/order_list.js
Labels: fe, debug

#86 [221201] [FE] 헤더 모바일 반응형 구현, 로고 추가, 홈 화면 캐러셀 및 슬라이드 CSS 수정
  src/views/event_page/event_page.css
  src/views/home/home.css
  src/views/home/home.html
  src/views/home/home.js
  src/views/img/logo.jpeg
  src/views/img/logo.png
  src/views/template/header/header.css
  src/views/template/header/header.js
Labels: fe, style
