Repository sojinjang/hansuldam, pull requests merged in 2022-12, with the labels that each got.

#87 [221201] [FE] 홈, 제품 상세 css 수정
  src/views/home/home.css
  src/views/home/home.html
  src/views/home/home.js
  src/views/product_detail/product_detail.css
Labels: fe, style

#88 [221201] [FE] 홈, 푸터 모바일 환경 CSS 수정 및 헤더 모바일 환경 장바구니 추가
  src/views/home/home.css
  src/views/template/footer/footer.css
  src/views/template/footer/footer.js
  src/views/template/header/header.css
  src/views/template/header/header.js
  src/views/template/main_style.css
Labels: fe, style

#89 [221201] [FE] 홈, 제품 상세 / 피드백 바탕으로 수정
  src/views/home/home.css
  src/views/home/home.html
  src/views/product_detail/product_detail.css
  src/views/product_detail/product_detail.js
  src/views/product_detail/review.css
Labels: fe, style

#90 [221201] [FE] 홈화면 슬라이더(화면 축소 시 폰트 반응형으로 적용)
  src/views/home/home.css
Labels: fe, style

#91 [221201] [FE] my_page로 파일명 변경
  src/routers/views-router.js
  src/views/join/join-success.css
  src/views/join/join.css
  src/views/login/login.css
  src/views/my_page/my_page.css
  src/views/my_page/my_page.html
  src/views/my_page/my_page.js
  src/views/order_list/order_list.js
Labels: fe, debug, style

#92 auth 로컬 주소 수정
  src/routers/naver-router.js
Labels: be

#95 [221202] [FE] 모바일 반응형 홈, 카테고리, 기획전, 상품 상세 페이지 CSS 수정
  src/views/category_page/category_page.css
  src/views/event_page/event_page.css
  src/views/home/home.css
  src/views/product_detail/product_detail.css
  src/views/product_detail/product_detail.js
  src/views/product_detail/review.css
Labels: fe, style

#96 [221202] [FE] 모바일 페이지에 맞게 css 수정
  src/routers/views-router.js
  src/views/adult_certification/adult_certification.css
  src/views/join/join-success.css
  src/views/join/join.css
  src/views/my_information/change_user_information.js
  src/views/my_information/my_information.css
  src/views/my_information/my_information.html
  src/views/my_information/my_information.js
  src/views/my_order_list/my_order_list.css
  src/views/my_order_list/my_order_list.html
  src/views/my_order_list/my_order_list.js
  src/views/my_page/my_page.css
  src/views/my_page/my_page.js
Labels: fe, style

#97 [221202] [FE] 마이페이지 css수정
  src/views/my_order_list/my_order_list.js
  src/views/my_page/my_page.css
Labels: fe, style

#98 [221202] [FE] 주문내역 css 수정
  src/views/join/join.css
  src/views/my_order_list/my_order_list.css
  src/views/my_page/my_page.css
Labels: fe, style

#99 [221202] [FE] 주문내역 배송지칸 css 수정
  src/views/my_order_list/my_order_list.css
  src/views/my_order_list/my_order_list.js
  src/views/my_page/my_page.css
  src/views/my_page/my_page.js
Labels: fe, style

#101 [221202] [FE] event_page 이미지 겹침 수정, 마진값 수정
  src/views/event_page/event_page.css
Labels: fe, debug, style

#103 [221207] [BE] 카테고리 페이지네이션 개선
  package-lock.json
  src/db/models/product-model.js
  src/routers/category-router.js
  src/services/category-service.js
Labels: be

#104 [221208] [FE] 상품금액 합계 오류 로직 수정
  src/views/my_order_list/my_order_list.js
Labels: fe

#105 [221209][BE] naver 로그인 url 변경
  src/routers/image-router.js
  src/routers/naver-router.js
Labels: be

#106 [221209] [FE] 총 상품 금액 함수 로직 수정, 정보 수정칸에 기존정보 뜨게 하기
  src/views/my_order_list/my_order_list.js
  src/views/my_page/my_page.js
Labels: fe, debug

#107 [221209] [FE] 총 상품합계 함수 로직 수정, 정보수정란에 기존정보 보이게 수정
  src/views/my_order_list/my_order_list.js
  src/views/my_page/my_page.js
Labels: fe, debug
